base_url = "https://super-botman.github.io"
theme = "neovim-theme"

[markdown]
highlight_code = true
highlight_theme = "ayu-mirage"

[extra]
blog_name="0xb0tm4n's website"
config_js = "config.js"
custom_css = "/css/intro.css"
