base_url = "https://super-botman.github.io"
theme = "zola-theme"

[markdown]
highlight_code = true
highlight_theme = "ayu-mirage"

[extra]
blog_name="0xb0tm4n's website"
custom_script = "/js/custom_script.js"
custom_css = "/css/intro.css"
