base_url = "https://super-botman.github.io"
theme = "neovim-theme"

[markdown]
render_emoji = true

[markdown.highlighting]
extra_themes = ["highlight_themes/tokyo-night.json"]
theme = "tokyo-night"

[extra]
blog_name="0xb0tm4n's website"
