name = "Arch btw"
description = "A only keyboard theme with tabs and file browser"
license = "MIT"
homepage = "https://github.com/super-botman/zola-theme"
# The minimum version of Zola required
min_version = "0.4.0"
# An optional live demo URL
demo = "https://super-botman.github.io"

# The theme author info: you!
[author]
name = "0xb0tm4n"
homepage = "https://super-botman.github.io"
